### ISSUE TITLE
UaException: Bad_NonceInvalid when connecting from inductiveautomation Ignition OPC Client

### ISSUE THREAD

**Issue by fautore** [locka99/opcua#150]
Hi everybody,
I set up a opcua-demo-server as in `samples/demo-server` and used the default configuration, then i set up an Ignition server on the same machine and created a new OPC Client connection to localhost port 4855.

the endpoint i'm setting into ignition is the following:
`opc.tcp://localhost:4855/`
but the Ignition OPC Client keeps faulting with the following error message:
` UaException: status=Bad_NonceInvalid, message=nonce must be non-zero`

I also tried fiddling with the configuration of the demo-server, i tried dropping the endpoints that use encryption but i seem to have no luck with this.

I also set up a opcua-simple-client that i found on `samples/simple-client/`, default configuration and that seems to work fine.

Any ideas / help with the configuration i am running?
Any help will be appreciated,
Thank you.

**Comment by schroeder-** [comment]
Which version are you using? Can you try current master? See issue #58 , which was fixed on master lately.

**Comment by fautore** [comment]
Yes, downloaded master and compiled it yesterday.

**Comment by schroeder-** [comment]
Maybe we have the same issue on the server side.
If you are using the configuration file try using this endpoint to force a password security policy:
```
 none:
    path: /
    security_policy: None
    security_mode: None
    security_level: 0
    password_security_policy: http://opcfoundation.org/UA/SecurityPolicy#Basic256
    user_token_ids:
      - ANONYMOUS
      - sample_password_user
      - sample_x509_user
```
Also does anonymous access with secruity_policy: None works?
