### ISSUE TITLE
Not able get library version 0.14.0

### ISSUE THREAD

**Issue by JaswanthP6878** [locka99/opcua#393]
Hello all,

I am not able to install 0.14.0 to use the async tokio functionality, The toml configuration is
```toml
[package]
name = "opc-project"
version = "0.1.0"
edition = "2021"

[dependencies]
opcua = { version = "0.14", features = ["client"] }
tokio = { version = "1", features = ["full"] }
```

and when i run using cargo run it is showing this error,
```bash
cargo run                                                                                                    ─╯
    Updating crates.io index
error: failed to select a version for the requirement `opcua = "^0.14"`
candidate versions found which didn't match: 0.12.0, 0.11.0, 0.10.0
location searched: crates.io index
required by package `opc-project v0.1.0 (/Users/jaswanthpinnepu/Desktop/projects/opc-project)`
perhaps a crate was updated and forgotten to be re-vendored?
```

Could some one explain how to use the library with version 0.14.0?

**Comment by AiyionPrime** [comment]
The latest tagged version is `0.12.0`, https://github.com/locka99/opcua/tags.
You can swap the version tag for a git reference to use main (the upcoming `0.13.0`):

https://doc.rust-lang.org/cargo/reference/specifying-dependencies.html#specifying-dependencies-from-git-repositories

```toml
[dependencies]
opcua = { git = "https://github.com/locka99/opcua.git", features = ["client"] }
```
