### ISSUE TITLE
"nonce must be non-zero" when trying to connect to OPC UA server from milo

### ISSUE THREAD

**Issue by evanjs** [locka99/opcua#43]
When attempting to connect to an OPC UA server configured with `ServerConfig::load` from a milo client, I am unable to connect to the server, and receive [this](https://github.com/eclipse/milo/blob/35ee06ea87676db9fdf4caf748b9265c40d1c841/opc-ua-stack/stack-core/src/main/java/org/eclipse/milo/opcua/stack/core/util/NonceUtil.java#L184) error message: "nonce must be non-zero".

According to [this comment](https://github.com/eclipse/milo/issues/575#issuecomment-558373517), I need to set the nonce whether security is enabled or not?
From what I've found in the samples, this can be done in the code, but I'm unsure how I can achieve this from a server configuration file.

Am I missing something with my configuration? Or is there something I need to do on the rust side?

<details>
 <summary>Current server.conf</summary>

``` 
---
application_name: OPC UA Sample Server
application_uri: "urn:OPC UA Sample Server"
product_uri: ""
pki_dir: "./pki"
create_sample_keypair: true
trust_client_certs: false
discovery_server_url: "opc.tcp://localhost:4840/UADiscovery"
tcp_config:
  hello_timeout: 5
  host: 0.0.0.0
  port: 4855
limits:
  clients_can_modify_address_space: false
  max_subscriptions: 100
  max_monitored_items_per_sub: 1000
  max_array_length: 1000
  max_string_length: 65536
  max_byte_string_length: 65536
  min_sampling_interval: 0.1
  min_publishing_interval: 0.1
user_tokens:
  sample_password_user:
    user: sample
    pass: sample1
  sample_x509_user:
    user: sample_x509
    x509: "./users/sample-x509.der"
  unused_user:
    user: unused
    pass: unused1
discovery_urls:
  - "opc.tcp://127.0.0.1:4855/"
endpoints:
  basic128rsa15_sign:
    path: /
    security_policy: Basic128Rsa15
    security_mode: Sign
    security_level: 2
    password_security_policy: ~
    user_token_ids:
      - ANONYMOUS
      - sample_password_user
      - sample_x509_user
  basic128rsa15_sign_encrypt:
    path: /
    security_policy: Basic128Rsa15
    security_mode: SignAndEncrypt
    security_level: 2
    password_security_policy: ~
    user_token_ids:
      - ANONYMOUS
      - sample_password_user
      - sample_x509_user
  basic256_sign:
    path: /
    security_policy: Basic256
    security_mode: Sign
    security_level: 3
    password_security_policy: ~
    user_token_ids:
      - ANONYMOUS
      - sample_password_user
      - sample_x509_user
  basic256_sign_encrypt:
    path: /
    security_policy: Basic256
    security_mode: SignAndEncrypt
    security_level: 3
    password_security_policy: ~
    user_token_ids:
      - ANONYMOUS
      - sample_password_user
      - sample_x509_user
  basic256sha256_sign:
    path: /
    security_policy: Basic256Sha256
    security_mode: Sign
    security_level: 4
    password_security_policy: ~
    user_token_ids:
      - ANONYMOUS
      - sample_password_user
      - sample_x509_user
  basic256sha256_sign_encrypt:
    path: /
    security_policy: Basic256Sha256
    security_mode: SignAndEncrypt
    security_level: 4
    password_security_policy: ~
    user_token_ids:
      - ANONYMOUS
      - sample_password_user
      - sample_x509_user
  no_access:
    path: /noaccess
    security_policy: None
    security_mode: None
    security_level: 1
    password_security_policy: ~
    user_token_ids: []
  none:
    path: /
    security_policy: None
    security_mode: None
    security_level: 1
    password_security_policy: ~
    user_token_ids:
      - ANONYMOUS
      - sample_password_user
      - sample_x509_user
```

</details>

Thanks!
