### ISSUE TITLE
User/Password authentification fails on SecurityPolicy#None

### ISSUE THREAD

**Issue by execuc** [locka99/opcua#58]
Hello,

I use your library, which is very good and reliable, as a client to connect to a opcua server. 
Server endpoint is described as :

```yaml
EndpointDescription
    EndpointUrl: opc.tcp://a.b.c.d:12345
    Server: ApplicationDescription
[...]
    MessageSecurityMode: None (0x00000001)
    SecurityPolicyUri: http://opcfoundation.org/UA/SecurityPolicy#None
    UserIdentityTokens: Array of UserTokenPolicy
        ArraySize: 1
        [0]: UserTokenPolicy
            PolicyId: UserName
            UserTokenType: UserName (0x00000001)
            IssuedTokenType: [OpcUa Null String]
            IssuerEndpointUrl: [OpcUa Null String]
            SecurityPolicyUri: http://opcfoundation.org/UA/SecurityPolicy#Basic128Rsa15
    TransportProfileUri: http://opcfoundation.org/UA-Profile/Transport/uatcp-uasc-uabinary
    SecurityLevel: 16
```

So there is no signature or encryption for message but password token has to be sent in RsaPkcs because of token Basic128Rsa15. But authentification is rejected by the server with a BadIdentityTokenInvalid error at ActivateSessionRequest state.

Token policy
------------

My first problem is I have to force the use of Basic128Rsa15 policy in `make_user_name_identity_token` function because the library seems to take the endpoint policy (None) instead of token policy resulting a clear password.

Is this a configuration problem on my side ?

Token content
-------------

My second problem is that authentication fails with the same error. In this case, the content of the token is incomplete before it is encrypted in `legacy_password_encrypt`. I noticed that the server_nonce is empty. In fact it is not set in `set_remote_nonce_from_byte_string` function because of endpoint None policy.

Is it a problem of endpoint/token mode of the server which is not possible in the opcua specifications or it is not managed by the library.

Thank you for your work
